# Generated by Django 5.1.7 on 2025-03-19 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genero',
            old_name='title',
            new_name='name',
        ),
    ]
