# Generated by Django 5.1.7 on 2025-03-19 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0002_rename_title_genero_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('tipo', models.CharField(default='', max_length=6)),
                ('description', models.TextField(blank=True, max_length=300)),
                ('url', models.URLField()),
                ('current_chapter', models.IntegerField()),
                ('on_going', models.BooleanField(default=True)),
                ('generos', models.TextField(default='')),
            ],
        ),
    ]
