# Generated by Django 5.1.7 on 2025-03-20 02:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0004_type_rename_id_genero_genero_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='ITEM_TYPE',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestor.type'),
        ),
    ]
