# Generated by Django 5.1.7 on 2025-03-20 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0005_alter_item_item_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='ITEM_ECRIPTION',
            new_name='ITEM_DESCRIPTION',
        ),
    ]
