# Generated by Django 5.1.7 on 2025-03-21 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0006_rename_item_ecription_item_item_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='ITEM_TYPE',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='gestor.type'),
        ),
    ]
